# Generated by Django 5.2.1 on 2025-05-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_movie_age_rating_movie_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('now_showing', 'Зараз в кінотеатрах'), ('coming_soon', 'Скоро у прокаті')], default='now_showing', max_length=20, verbose_name='Статус'),
        ),
    ]
