# Generated by Django 5.2.1 on 2025-06-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Тривалість (хв)'),
        ),
    ]
