# Generated by Django 5.2.1 on 2025-06-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_movie_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.TextField(blank=True, null=True, verbose_name='У головних ролях'),
        ),
        migrations.AddField(
            model_name='movie',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Виробництво'),
        ),
    ]
