# Generated by Django 5.2.1 on 2025-06-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_movie_actors_movie_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на трейлер (YouTube)'),
        ),
    ]
