# Generated by Django 5.2.1 on 2025-06-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_movie_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieschedule',
            name='vip_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ціна VIP квитків'),
        ),
    ]
