# Generated by Django 5.2.1 on 2025-06-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_movieschedule_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='movie_posters/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='movieschedule',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='movieschedule',
            name='hall',
            field=models.CharField(max_length=50, verbose_name='Зал'),
        ),
        migrations.AlterField(
            model_name='movieschedule',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=200.0, max_digits=6, null=True, verbose_name='Ціна квитків'),
        ),
        migrations.AlterField(
            model_name='movieschedule',
            name='time',
            field=models.TimeField(verbose_name='Час'),
        ),
    ]
