# Generated by Django 5.2.1 on 2025-06-03 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_movie_poster_alter_movieschedule_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieschedule',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='movieschedule',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Час'),
        ),
    ]
