# Generated by Django 5.2.1 on 2025-06-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_movieschedule_date_alter_movieschedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieschedule',
            name='hall',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Зал'),
        ),
    ]
