# Generated by Django 5.2.1 on 2025-06-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_movieschedule_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='display_on_website',
            field=models.BooleanField(default=True, verbose_name='Відображати на сайті'),
        ),
    ]
