# Generated by Django 5.2.1 on 2025-06-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_purchasedseat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieschedule',
            name='vip_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=350.0, max_digits=6, null=True, verbose_name='Ціна VIP квитків'),
        ),
    ]
