# Generated by Django 5.2.1 on 2025-06-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_movieschedule_vip_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedseat',
            name='price_at_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ціна на момент покупки'),
        ),
    ]
